### ISSUE TITLE
Compilation issues in Debian bullseye: 198>38 TTF_HINTING_LIGHT_SUBPIXEL

### ISSUE THREAD

**Issue by zenny** [RaphGL/NeoSent#4]
Hi,

Trying to build in Debian 11 gives the following error. All required dev libraries are installed, fyi,
```
src/render.c:198:38: error: ‘TTF_HINTING_LIGHT_SUBPIXEL’ undeclared (first use in this function); did you mean ‘TTF_HINTING_LIGHT’?
  198 |   TTF_SetFontHinting(renderer->font, TTF_HINTING_LIGHT_SUBPIXEL);
```

Changed to `TTF_HINTING_LIGHT` and the compilation failed againg:

```
src/render.c:196:3: warning: implicit declaration of function ‘TTF_SetFontSize’; did you mean ‘TTF_SetFontStyle’? [-Wimplicit-function-declaration]
  196 |   TTF_SetFontSize(renderer->font, win_size.x / text_len);
      |   ^~~~~~~~~~~~~~~
      |   TTF_SetFontStyle
make: *** [Makefile:21: render.o] Error 1
```
Changed to `TTF_SetFontStyle` and got:

```
src/render.c:44:53: error: ‘IMG_INIT_AVIF’ undeclared (first use
in this function); did you mean ‘IMG_INIT_TIF’?
   44 | MG_INIT_JPG | IMG_INIT_PNG | IMG_INIT_WEBP | IMG_INIT_AVIF;
      |                                              ^~~~~~~~~~~~~
      |                                              IMG_INIT_TIF
src/render.c:44:53: note: each undeclared identifier is reported
only once for each function it appears in
make: *** [Makefile:21: render.o] Error 1
```

fyi.

Cheers

**Comment by RaphGL** [comment]
Yeah these issues are occurring because of the SDL2 version on Debian. I've fixed the hinting issue (turns out I don't needed it at all). 
IMG_INIT_AVIF requires you to have SDL2_image 2.6 at least, Debian Bullseye seems to be at 2.0 still.

**Comment by RaphGL** [comment]
let me know if you still have problems compiiling the project

**Comment by zenny** [comment]
@RaphGL  Thanks for the prompt response.

However, it does not seem to be possible to compile in Debian 11 due to the old version of the libraries. It would be nice if you can post a backward-compatible binary `nsent` because the binary at https://github.com/RaphGL/NeoSent/releases/download/v1.2/nsent_linux_v1.2_x86_64 also shows up the following dependency hell in debian 11:

```
./nsent_linux_v1.2_x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./nsent_linux_v1.2_x86_64)
``

Thanks

**Comment by RaphGL** [comment]
You're on x86 correct? Try this
[nsent.zip](https://github.com/RaphGL/NeoSent/files/11713270/nsent.zip)

I'm trying to statically link SDL2 for you but I'm not sure how

**Comment by zenny** [comment]
> You're on x86 correct? Try this [nsent.zip](https://github.com/RaphGL/NeoSent/files/11713270/nsent.zip)
> 
> I'm trying to statically link SDL2 for you but I'm not sure how

x86_64

**Comment by RaphGL** [comment]
yeah the binary I sent u is for x86_64

**Comment by zenny** [comment]
> yeah the binary I sent u is for x86_64

I got.

```
./nsent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./nsent)
```

**Comment by RaphGL** [comment]
ok this took me a while to figure out
I tried compiling to ur libc version by using the zig toolchain
[nsent.zip](https://github.com/RaphGL/NeoSent/files/11713328/nsent.zip)

see if it works (I have no idea)

**Comment by zenny** [comment]
> ok this took me a while to figure out I tried compiling to ur libc version by using the zig toolchain [nsent.zip](https://github.com/RaphGL/NeoSent/files/11713328/nsent.zip)
> 
> see if it works (I have no idea)

Nope, same dependency error.
 Anyway thanks for your efforts.

**Comment by RaphGL** [comment]
I'm trying to figure out how to compile for your libc version, I can do it with the `zig cc` toolchain, but I'm not sure if this works
[nsent.zip](https://github.com/RaphGL/NeoSent/files/11713338/nsent.zip)
(updated after consulting with some people in the zig channels but even they are not sure)

**Comment by zenny** [comment]
> I'm trying to figure out how to compile for your libc version, I can do it with the `zig cc` toolchain, but I'm not sure if this works [nsent.zip](https://github.com/RaphGL/NeoSent/files/11713338/nsent.zip) (updated after consulting with some people in the zig channels but even they are not sure)

Anyway even with the latest zip, the dependency hell is there (GLIBC_2.34)

**Comment by RaphGL** [comment]
yeah C sucks for this, should've written it in rust or something to avoid this problem
I can't even tell what the issue with libc is here.

**Comment by zenny** [comment]
> yeah C sucks for this, should've written it in rust or something to avoid this problem I can't even tell what the issue with libc is here.

Yep.
